# Generated by Django 3.0.8 on 2020-07-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'select'), ('ORG', 'Organic Formulations'), ('BODY CARE', 'Body Care')], default='select', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
