# Generated by Django 3.0.8 on 2020-07-21 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_frequentlyaskedquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequentlyaskedquestion',
            old_name='ques_slug',
            new_name='slug',
        ),
    ]
