# Generated by Django 3.0.8 on 2020-07-22 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200721_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequentlyaskedquestion',
            name='slug',
        ),
    ]
