# Generated by Django 3.0.8 on 2020-09-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_frequentlyaskedquestion_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='add_vat',
            field=models.BooleanField(default=False),
        ),
    ]
