# Generated by Django 3.0.8 on 2020-09-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200927_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='add_tax',
            field=models.BooleanField(default=False),
        ),
    ]
