# Generated by Django 3.0.8 on 2020-09-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200927_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='add_vat',
        ),
    ]
