# Generated by Django 3.0.8 on 2020-10-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200927_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_vat', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='add_vat',
        ),
    ]
