# Generated by Django 3.0.8 on 2020-10-07 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201007_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addtax',
            options={'verbose_name': 'tax', 'verbose_name_plural': 'tax'},
        ),
    ]
