# Generated by Django 3.0.8 on 2020-10-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20201007_1017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddTax',
        ),
    ]
