# Generated by Django 2.2.4 on 2020-06-19 17:50

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('email_address', models.EmailField(max_length=254)),
                ('company_or_business_name', models.CharField(max_length=255)),
                ('business_address_line_1', models.CharField(max_length=512)),
                ('business_address_line_2', models.CharField(blank=True, max_length=512, null=True)),
                ('state_or_province', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('business_phone_number', models.CharField(blank=True, max_length=19, null=True)),
                ('website', models.URLField(max_length=160, null=True)),
                ('product_type', models.CharField(choices=[('supplements & vitamins', 'Supplements & Vitamins'), ('beauty', 'Beauty'), ('body care', 'Body Care'), ('herbal supplements', 'Herbal Supplements'), ('conditioners', 'Conditioners'), ('nutritions', 'Nutritions')], max_length=255)),
                ('product_features_and_benefits', models.TextField(max_length=2500)),
                ('business_category', models.CharField(choices=[('manu', 'Manufacturering'), ('packaging', 'Packaging'), ('retailer', 'Retail'), ('marketing', 'Marketing & Supplies')], max_length=200)),
            ],
        ),
    ]
