# Generated by Django 2.2.4 on 2020-06-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_auto_20200620_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerjoin',
            name='zip_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
