# Generated by Django 2.2.4 on 2020-06-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_auto_20200620_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerjoin',
            name='business_category',
            field=models.CharField(choices=[('', 'select'), ('manu', 'Manufacturing'), ('packaging', 'Packaging'), ('retailer', 'Retail'), ('marketing', 'Marketing & Supplies')], default='select', max_length=200),
        ),
        migrations.AlterField(
            model_name='partnerjoin',
            name='product_type',
            field=models.CharField(choices=[('', 'select'), ('supplements & vitamins', 'Supplements & Vitamins'), ('beauty', 'Beauty'), ('body care', 'Body Care'), ('herbal supplements', 'Herbal Supplements'), ('conditioners', 'Conditioners'), ('nutritions', 'Nutritions')], default='select', max_length=255),
        ),
    ]
