# Generated by Django 2.2.4 on 2020-06-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_auto_20200620_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerjoin',
            name='website',
            field=models.URLField(blank=True, max_length=160, null=True),
        ),
    ]
