# Generated by Django 2.2.4 on 2020-06-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_auto_20200620_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerjoin',
            name='website',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
