# Generated by Django 2.2.4 on 2020-06-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_sellapply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellapply',
            name='selling_price',
            field=models.CharField(max_length=19),
        ),
    ]
