# Generated by Django 2.2.4 on 2020-06-21 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_auto_20200621_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellapply',
            options={'verbose_name': 'sell_item_application', 'verbose_name_plural': 'sell_item_applications'},
        ),
    ]
