# Generated by Django 2.2.4 on 2020-06-21 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_auto_20200621_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellapply',
            options={'verbose_name': 'Sell Item Application', 'verbose_name_plural': 'Sell Item Applications'},
        ),
    ]
