# Generated by Django 2.2.4 on 2020-06-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_auto_20200621_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellapply',
            name='date_produced',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='sellapply',
            name='expiry_date',
            field=models.DateField(blank=True),
        ),
    ]
