# Generated by Django 2.2.4 on 2020-06-22 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0012_auto_20200622_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellapply',
            name='product_sku',
        ),
    ]
