# Generated by Django 2.2.4 on 2020-06-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0013_remove_sellapply_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellapply',
            name='date_produced',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellapply',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
