# Generated by Django 2.2.4 on 2020-06-22 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0014_auto_20200622_0243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellapply',
            options={},
        ),
    ]
