# Generated by Django 2.2.4 on 2020-06-22 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0015_auto_20200622_0245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellapply',
            options={'verbose_name': 'Sell Item Application', 'verbose_name_plural': 'Sell Item Applications'},
        ),
    ]
