# Generated by Django 2.2.4 on 2020-06-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0016_auto_20200622_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellapply',
            name='image',
        ),
    ]
