# Generated by Django 2.2.4 on 2020-06-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0017_remove_sellapply_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellapply',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
