# Generated by Django 2.2.4 on 2020-06-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0019_remove_sellapply_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BecomeDistributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=60)),
                ('age', models.CharField(max_length=2)),
                ('gender', models.CharField(choices=[('', 'select'), ('f', 'female'), ('m', 'male')], max_length=8)),
                ('valid_contact_address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=19, null=True)),
                ('i_operate_as', models.CharField(choices=[('', 'select'), ('company', 'Company'), ('individual', 'Individual')], max_length=19)),
                ('next_of_kin_name', models.CharField(max_length=160)),
                ('next_of_kin_address', models.CharField(max_length=160)),
                ('next_of_kin_phone_number', models.CharField(max_length=160)),
                ('next_of_kin_engagement', models.CharField(choices=[('', 'select'), ('employed', 'Employed'), ('self employed', 'Self Employed'), ('Unemployed', 'Unemployed')], max_length=50)),
            ],
        ),
    ]
