# Generated by Django 2.2.4 on 2020-06-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0020_becomedistributor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='becomedistributor',
            old_name='valid_contact_address',
            new_name='contact_address',
        ),
    ]
