# Generated by Django 2.2.4 on 2020-07-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0021_auto_20200630_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(choices=[('', 'select'), ('internet', 'Internet'), ('newspaper', 'Newspaper'), ('facebook', 'Facebook'), ('google', 'Google')], max_length=60)),
            ],
            options={
                'verbose_name': 'medium',
                'verbose_name_plural': 'media',
            },
        ),
        migrations.RemoveField(
            model_name='becomedistributor',
            name='next_of_kin_address',
        ),
        migrations.RemoveField(
            model_name='becomedistributor',
            name='next_of_kin_engagement',
        ),
        migrations.RemoveField(
            model_name='becomedistributor',
            name='next_of_kin_name',
        ),
        migrations.RemoveField(
            model_name='becomedistributor',
            name='next_of_kin_phone_number',
        ),
        migrations.AddField(
            model_name='becomedistributor',
            name='daily_sales_qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='becomedistributor',
            name='demand_level',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='becomedistributor',
            name='weekly_sales_qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='becomedistributor',
            name='heared_about_us_via',
            field=models.ManyToManyField(to='program.MediaType'),
        ),
    ]
