# Generated by Django 2.2.4 on 2020-07-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0022_auto_20200701_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becomedistributor',
            name='heared_about_us_via',
            field=models.ManyToManyField(to='program.MediaType', verbose_name='seleted media types'),
        ),
    ]
