# Generated by Django 2.2.4 on 2020-07-01 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0023_auto_20200701_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='becomedistributor',
            old_name='heared_about_us_via',
            new_name='media_type',
        ),
    ]
