# Generated by Django 2.2.4 on 2020-07-01 18:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0025_auto_20200701_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='becomedistributor',
            name='media_type',
        ),
        migrations.AddField(
            model_name='becomedistributor',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('internet', 'Internet'), ('newspaper', 'Newspaper'), ('facebook', 'Facebook'), ('google', 'Google')], default=None, max_length=34),
        ),
        migrations.DeleteModel(
            name='MediaType',
        ),
    ]
