# Generated by Django 2.2.4 on 2020-07-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0027_auto_20200701_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becomedistributor',
            name='contact_address',
            field=models.CharField(max_length=1500),
        ),
    ]
