# Generated by Django 2.2.4 on 2020-07-02 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0028_auto_20200701_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='becomedistributor',
            name='medium',
        ),
    ]
