# Generated by Django 2.2.4 on 2020-07-02 07:39

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0029_remove_becomedistributor_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='becomedistributor',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('internet', 'Internet'), ('newspaper', 'Newspaper'), ('facebook', 'Facebook'), ('google', 'Google')], default=None, max_length=34),
        ),
        migrations.AlterField(
            model_name='becomedistributor',
            name='age',
            field=models.IntegerField(max_length=2),
        ),
    ]
