# Generated by Django 2.2.4 on 2020-07-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0030_auto_20200702_0739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='becomedistributor',
            options={'verbose_name': 'Distributor Application', 'verbose_name_plural': 'Distributor Applications'},
        ),
        migrations.RemoveField(
            model_name='becomedistributor',
            name='i_operate_as',
        ),
        migrations.AddField(
            model_name='becomedistributor',
            name='i_apply_as',
            field=models.CharField(choices=[('', 'select'), ('company', 'Company'), ('individual', 'Individual')], default='select', max_length=19),
        ),
    ]
