# Generated by Django 2.2.4 on 2020-07-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0031_auto_20200702_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becomedistributor',
            name='age',
            field=models.IntegerField(),
        ),
    ]
