# Generated by Django 3.0.8 on 2020-07-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0032_auto_20200702_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becomedistributor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='becomedistributor',
            name='full_name',
            field=models.CharField(max_length=60),
        ),
    ]
